version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for `requirements.txt` and `setup.py` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "python"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10
    # Set a prefix for commit messages
    commit-message:
      prefix: "pip"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "github-actions"
      include: "scope"